server:
  port: 9091
  servlet:
    context-path: /user-details
  
spring:
  application:
    name: User-Service
  datasource:
      url: jdbc:postgresql://localhost:5432/RatingMicroservicesDB
      username: postgres
      password: prashik 
      driver-class-name: org.postgresql.Driver
  config:
    import: optional:configserver:http:localhost:9095
    
    
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
    
resilience4j:
  circuitbreaker:
    instances:
      ratingHotelCircuitBreaker:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 6s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
  retry:
    instances:
      ratingHotelRetry:
        max-attempts: 3
        wait-duration: 3s
  ratelimiter:
    instances:
      ratingHotelRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 2      
logging:
  file:
    name: E:\logs\user-service.log 
       
    #  jpa:
    #    hibernate:
    #      ddl-auto: update
    #    show-sql: true
    #    
    #eureka:
    #  client:
    #    service-url:
    #      defaultZone: http://localhost:8761/eureka
    #